
import os
import logging
import gradio as gr
from orchestrator import MultiAgentOrchestrator

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def run_pipeline(topic: str, api_key: str, progress=gr.Progress(track_tqdm=True)):
    """Called when user clicks the button in the UI."""

    if not api_key.strip():
        return "❌ Please enter your OpenAI API key.", "", ""
    if not topic.strip():
        return "❌ Please enter a research topic.", "", ""

    orchestrator = MultiAgentOrchestrator(api_key=api_key.strip())

    step_messages = [
        (0.10, "🔒 Security Agent: Validating input..."),
        (0.30, "🗺️  Planner Agent (LangGraph): Creating research plan..."),
        (0.55, "🔬 Research Crew (CrewAI): Researching and analyzing..."),
        (0.75, "📝 Report Writer (Semantic Kernel): Generating report..."),
        (0.90, "🔍 Critic Agent (LangChain): Reviewing report..."),
    ]
    step_idx = [0]

    def tick(msg):
        if step_idx[0] < len(step_messages):
            pct, label = step_messages[step_idx[0]]
            progress(pct, desc=label)
            step_idx[0] += 1

    result = orchestrator.run(topic, progress_cb=tick)
    progress(1.0, desc="✅ Complete!")

    if not result["success"]:
        return result.get("error", "An error occurred."), "", ""

    # ── Format agent log ────────────────────────────────────────────────────
    log_lines = []
    for e in result["log"]:
        icon = "✅" if e["status"] == "success" else "❌" if e["status"] == "error" else "🔄"
        log_lines.append(f"{icon} `[{e['time']}]` **{e['step']}**: {e['detail']}")
    log_md = "\n\n".join(log_lines)

    # ── Format research plan ────────────────────────────────────────────────
    plan_md = (
        "### 🗺️ Research Plan (generated by LangGraph Planner Agent)\n\n"
        + "\n".join([f"- **{s}**" for s in result.get("subtopics", [])])
    )

    return result["report"], plan_md, log_md


# ── Build the Gradio UI ──────────────────────────────────────────────────────
with gr.Blocks(
    title="Multi-Agent Research Generator",
    theme=gr.themes.Soft(),
) as demo:

    gr.Markdown("""
    # 🤖 Multi-Agent Research Report Generator
    ### Wipro Junior FDE Pre-screening Demo

    ---
    **Agent Pipeline:** 🔒 Security (Custom) → 🗺️ Planner (LangGraph) → 🔬 Research Crew (CrewAI) → 📝 Report Writer (Semantic Kernel) → 🔍 Critic (LangChain)
    """)

    with gr.Row():
        with gr.Column(scale=1):
            api_key_box = gr.Textbox(
                label="🔑 OpenAI API Key",
                placeholder="sk-...",
                type="password",
                info="Your key is never stored or logged."
            )
            topic_box = gr.Textbox(
                label="📚 Research Topic",
                placeholder="e.g., Artificial Intelligence in Healthcare",
                lines=2,
                info="Enter any research topic (max 500 characters)"
            )
            gr.Examples(
                examples=[
                    "Artificial Intelligence in Healthcare",
                    "Climate Change Solutions",
                    "Quantum Computing Fundamentals",
                    "Sustainable Energy Technologies",
                    "Cybersecurity Best Practices",
                ],
                inputs=topic_box,
            )
            submit_btn = gr.Button("🚀 Generate Report", variant="primary", size="lg")

            gr.Markdown("""
            ---
            ### 🏗️ Frameworks Used
            | Agent | Framework |
            |---|---|
            | 🔒 Security | Custom Python |
            | 🗺️ Planner | LangGraph |
            | 🔬 Researcher | CrewAI |
            | 📊 Analyst | CrewAI |
            | 📝 Report Writer | Semantic Kernel |
            | 🔍 Critic | LangChain |
            | 🤝 Coordinator | Custom Orchestrator |
            """)

        with gr.Column(scale=2):
            with gr.Tab("📄 Final Report"):
                report_out = gr.Markdown("*Your report will appear here...*")
            with gr.Tab("🗺️ Research Plan"):
                plan_out = gr.Markdown("*Research plan will appear here...*")
            with gr.Tab("📊 Agent Execution Log"):
                log_out = gr.Markdown("*Execution log will appear here...*")

    submit_btn.click(
        fn=run_pipeline,
        inputs=[topic_box, api_key_box],
        outputs=[report_out, plan_out, log_out],
        show_progress=True,
    )

    gr.Markdown("---\n*Built for Wipro Junior FDE Pre-screening | Multi-Agent System*")


if __name__ == "__main__":
    demo.launch(
        server_name="0.0.0.0",
        server_port=int(os.environ.get("PORT", 7860)),
        share=False
    )
