
import logging
import asyncio
import nest_asyncio
import semantic_kernel as sk
from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion
from semantic_kernel.functions import KernelArguments

logger = logging.getLogger(__name__)

# Allow asyncio in Jupyter/Colab environments
nest_asyncio.apply()

# ── Prompt template ───────────────────────────────────────────────────────────
REPORT_PROMPT = """
You are a professional technical report writer.

Topic: {{$topic}}

Research Findings:
{{$research}}

Analysis:
{{$analysis}}

Write a professional, structured research report with these sections:

# {{$topic}} — Research Report

## Executive Summary
(2–3 sentences summarizing the entire report)

## Introduction
(Brief overview of the topic and why it matters)

## Key Findings
(Bullet points of the most important research findings)

## Analysis & Insights
(Key analytical conclusions and what they mean)

## Conclusion
(Main takeaways and recommendations)

---
*Report generated by Multi-Agent AI System*

Use markdown formatting. Be professional and informative.
"""


async def _async_generate_report(topic: str, research: str, analysis: str, api_key: str) -> str:
    """Async report generation using Semantic Kernel."""
    kernel = sk.Kernel()

    # Register the OpenAI chat service with the kernel
    kernel.add_service(
        OpenAIChatCompletion(
            service_id="openai_chat",
            ai_model_id="gpt-3.5-turbo",
            api_key=api_key,
        )
    )

    # Register the prompt as a kernel function (plugin/skill)
    report_fn = kernel.add_function(
        function_name="write_report",
        plugin_name="ReportPlugin",
        prompt=REPORT_PROMPT,
        description="Generates a professional research report from gathered data.",
    )

    # Invoke the function with arguments
    result = await kernel.invoke(
        report_fn,
        KernelArguments(
            topic=topic,
            research=research[:2500],   # Token budget management
            analysis=analysis[:1200],
        )
    )
    return str(result)


def generate_report(topic: str, research: str, analysis: str, api_key: str) -> str:
    """Synchronous wrapper — generates report using Semantic Kernel."""
    logger.info(f"Semantic Kernel: Generating report for '{topic}'")
    try:
        loop = asyncio.get_event_loop()
        report = loop.run_until_complete(
            _async_generate_report(topic, research, analysis, api_key)
        )
        logger.info("Semantic Kernel: Report generated ✅")
        return report
    except Exception as e:
        logger.error(f"Semantic Kernel error: {e}")
        # Graceful fallback report
        return f"""# {topic} — Research Report

## Executive Summary
This report summarizes key findings about {topic}.

## Key Findings
{research[:600]}

## Analysis
{analysis[:400]}

## Conclusion
Further research on {topic} is recommended based on these findings.

---
*Report generated by Multi-Agent AI System*
"""
